steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'MODEL_SIZES=${_MODEL_SIZES}'
      - '-t'
      - '${_IMAGE_TAG}'
      - '.'
    timeout: '3600s'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_TAG}']
substitutions:
  _MODEL_SIZES: '0.6B,1.7B'
images:
  - '${_IMAGE_TAG}'
timeout: '3600s'
options:
  machineType: 'E2_HIGHCPU_32'
