steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--target'
      - 'runtime-${_BUILD_PROFILE}'
      - '--build-arg'
      - 'BUILD_PROFILE=${_BUILD_PROFILE}'
      - '--build-arg'
      - 'MODEL_SIZES=${_MODEL_SIZES}'
      - '--build-arg'
      - 'MODEL_ID_0_6B=${_MODEL_ID_0_6B}'
      - '--build-arg'
      - 'MODEL_ID_1_7B=${_MODEL_ID_1_7B}'
      - '--build-arg'
      - 'VOICE_DESIGN_ENABLED=${_VOICE_DESIGN_ENABLED}'
      - '--build-arg'
      - 'VOICE_DESIGN_MODEL_ID=${_VOICE_DESIGN_MODEL_ID}'
      - '-t'
      - '${_IMAGE_TAG}'
      - '.'
    timeout: '3600s'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_TAG}']
substitutions:
  _BUILD_PROFILE: 'full'
  _MODEL_SIZES: '1.7B'
  _MODEL_ID_0_6B: 'Qwen/Qwen3-TTS-12Hz-0.6B-Base'
  _MODEL_ID_1_7B: 'Qwen/Qwen3-TTS-12Hz-1.7B-Base'
  _VOICE_DESIGN_ENABLED: 'false'
  _VOICE_DESIGN_MODEL_ID: 'Qwen/Qwen3-TTS-12Hz-1.7B-VoiceDesign'
images:
  - '${_IMAGE_TAG}'
timeout: '3600s'
options:
  machineType: 'E2_HIGHCPU_32'
